unit Consts;

interface

type
  string1 = string[1];
  string2 = string[2];
  string3 = string[3];
  string4 = string[4];
  string5 = string[5];
  string6 = string[6];
  string7 = string[7];
  string8 = string[8];
  string9 = string[9];
  string10 = string[10];
  string11 = string[11];
  string12 = string[12];
  string13 = string[13];
  string14 = string[14];
  string15 = string[15];
  string16 = string[16];
  string17 = string[17];
  string18 = string[18];
  string19 = string[19];
  string20 = string[20];
  string25 = string[25];
  string30 = string[30];
  string35 = string[35];
  string40 = string[40];
  string45 = string[45];
  string50 = string[50];
  string75 = string[75];
  string100 = string[100];


const
  DefaultListCapacity = 16;

implementation

end.